### ISSUE TITLE
RFC2822: UTC should be indicated by "+0000", not "U"

### ISSUE THREAD

**Issue by mscha** [supernovus/perl6-datetime-format#15]
`U` is a non-standard way to indicate time zone UTC in RFC2822.
The RFC states:

> The form "+0000" SHOULD be used to indicate a time zone at Universal Time. 

The only documented "obsolete" time zone indicators for UTC are `UT` and `GMT`.  But it's better to stick with the recommendation and use numeric time zones only, i.e. `+0000` for UTC.

Example:

    perl6 -MDateTime::Format::RFC2822 -e 'say DateTime::Format::RFC2822.to-string(DateTime.new(1522146738))'

Expected result:

    Tue, 27 Mar 2018 10:32:18 +0000

Actual result:

    Tue, 27 Mar 2018 10:32:18 Z

See: https://www.ietf.org/rfc/rfc2822.txt

**Comment by supernovus** [comment]
It's been a while since I looked at this library, but the 'Z' is coming straight from the ISO 8601 standard which Perl 6 uses internally in it's DateTime objects.
https://en.wikipedia.org/wiki/ISO_8601

All of the DateTime::Format::* classes are using the DateTime::Format strftime() method behind the scenes, and as of this post, only had one option for the timezone portion, which used 'Z' to represent UTC as that's what Perl 6 itself uses. I will look at adding an extra option which uses '+0000' instead, and updating the DateTime::Format::RFC2822 library to use the new option.
